name: github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          run: npm install
          run: npm run build
      - name: Generate Coverage Report
          run: npm run test
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ env.CODECOV_TOKEN }}
          directory: ./tests/
          files: ./lcov.info, ./coverage-final.json
          flags: unittests